### ISSUE TITLE
add sesheta as a collaborator

### ISSUE THREAD

**Issue by goern** [fridex/thoth-user-api#50]
so that Jenkins can build PRs against your repo

**Comment by goern** [comment]
please grant push access as...

```
ERROR: [Tue Apr 10 11:21:10 UTC 2018] Could not fetch sources from navigator org.jenkinsci.plugins.github_branch_source.GitHubSCMNavigator@2baa3ab0
java.io.FileNotFoundException: https://api.github.com/repos/fridex/thoth-user-api/collaborators/goern/permission
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:243)
	at com.squareup.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
	at com.squareup.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
	at org.kohsuke.github.Requester.parse(Requester.java:612)
	at org.kohsuke.github.Requester.parse(Requester.java:594)
	at org.kohsuke.github.Requester._to(Requester.java:272)
Caused: org.kohsuke.github.GHFileNotFoundException: {"message":"Must have push access to view collaborator permission.","documentation_url":"https://developer.github.com/v3/repos/collaborators/#review-a-users-permission-level"}
```

**Comment by fridex** [comment]
Invitation sent, thanks!
